#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx nx affected --base=origin/dev -t lint --parallel=3
npx nx affected --base=origin/dev -t spell --parallel=3
npx nx affected --base=origin/dev -t test --parallel=3 --configuration=ci
npx nx affected --base=origin/dev -t build --parallel=3
