import { iMap, map, nMap, xIMap } from '@blackhole/keybinding-manager';

export enum Actions {
  MoveNextBlock = 'MoveNextBlock',
  MovePrevBlock = 'MovePrevBlock',
  MoveToLastBlock = 'MoveToLastBlock',
  MoveToFirstBlock = 'MoveToFirstBlock',
  GoToEditMode = 'GoToEditMode',
  Insert = 'Insert',
  GoToNormalMode = 'GoToNormalMode',
  CreateTask = 'CreateTask',
  SaveTask = 'SaveTask',
  DeleteTask = 'DeleteTask',
  CloseModal = 'CloseModal',
  Toggle = 'Toggle',
  Focus = 'Focus',
  MoveDown = 'MoveDown',
  MoveUp = 'MoveUp',
  ShowHelp = 'ShowHelp',
  ShowSelectProject = 'ShowSelectProject',
  ToggleDoneVisibility = 'ToggleDoneVisibility',
  Undo = 'Undo',
  SelectProject = 'SelectProject',
  Open = 'Open',
  SignIn = 'SignIn',
}

// cspell:disable
export const keyMaps = {
  [Actions.MoveNextBlock]: xIMap('j', 'arrowdown'),
  [Actions.MovePrevBlock]: xIMap('k', 'arrowup'),
  [Actions.MoveToLastBlock]: xIMap('shift+g'),
  [Actions.MoveToFirstBlock]: xIMap('g,g'),
  [Actions.GoToEditMode]: nMap('a'),
  [Actions.GoToNormalMode]: iMap('capslock', 'escape'),
  [Actions.CreateTask]: nMap('c'),
  [Actions.SaveTask]: iMap('enter'),
  [Actions.CloseModal]: map('capslock', 'escape'),
  [Actions.Toggle]: nMap(' '),
  [Actions.DeleteTask]: nMap('d'),
  [Actions.MoveUp]: nMap('alt+k'),
  [Actions.MoveDown]: nMap('alt+j'),
  [Actions.ShowHelp]: nMap('h'),
  [Actions.Focus]: nMap('f'),
  [Actions.ToggleDoneVisibility]: nMap('.'),
  [Actions.Undo]: nMap('u'),
  [Actions.Insert]: nMap('i'),
  [Actions.ShowSelectProject]: nMap('p'),
  [Actions.SelectProject]: xIMap('enter'),
  [Actions.Open]: nMap('o'),
  [Actions.SignIn]: nMap('ctrl+shift+l'),
} as const;
// cspell:enable
