#!/usr/bin/env sh

set -e

pnpm nx affected --base=origin/dev --output-style=dynamic --nxBail=true -t lint
pnpm nx affected --base=origin/dev --output-style=dynamic --nxBail=true -t tsc
pnpm nx affected --base=origin/dev --output-style=dynamic --nxBail=true -t spell
pnpm nx affected --base=origin/dev --output-style=dynamic --nxBail=true -t build
pnpm nx affected --base=origin/dev --output-style=dynamic --nxBail=true -t test --configuration=ci
